server:
    address: 127.0.0.1
    contextPath: /
    port: 8080
    tomcat:
        backgroundProcessorDelay: 30
        basedir: ''
        protocolHeader: x-forwarded-proto
        remoteIpHeader: x-forwarded-for
spring:
    thymeleaf:
        cache: false
        content-type: text/html
        encoding: UTF-8
        mode: HTML5
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:pavilion.db
        username: root
        password: 123456